# Configuração da conexão com o MySQL (lida pela ConexaoFactory)
db.url=jdbc:mysql://localhost:3306/cinema?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
db.user=root
db.password=univille
